repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        stages:
          - pre-commit
      - id: ruff-format
        stages:
          - pre-commit

  - repo: https://github.com/PyCQA/pylint
    rev: "v3.2.3"
    hooks:
      - id: pylint
        stages:
          - pre-commit